apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: Bookstore
        image: 600627363311.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
        ports:
        - containerPort: 80